### ISSUE TITLE
we need to update artifactory url here?

### ISSUE THREAD

**Issue by sharathkumarnp** [Lior-Asher/JFrog-Artifactory-CLI#5]
https://github.com/Lior-Asher/JFrog-Artifactory-CLI/blob/98d0edfef3a59b67a503967e56b9577b9309f056/app.py#L29

**Comment by Lior-Asher** [comment]
Only the Artifactory server name you will use here:
self.url = f'https://{**self.server**}.jfrog.io/artifactory/api/'

**Comment by sharathkumarnp** [comment]
Im receiving this error,

    from secrets import SERVER
> ImportError: cannot import name 'SERVER' from 'secrets'

**Comment by Lior-Asher** [comment]
secrets.py is another file, in the same directory as app.py file, where I keep private data such as server name.
To fix the error add another python file named "secrets.py".
In it add the line: SERVER='your_server_name' (your Artifactory server)

The line is importing a value from another python file.

**Comment by sharathkumarnp** [comment]
Thanks,

Can you please share me what all values I need to import from secrets.py
file.. after adding servers and username .etc im still receiving few errors:

**Comment by Lior-Asher** [comment]
It includes only server name for this project.
What other errors you get?

**Comment by sharathkumarnp** [comment]
`usage: test.py [-h] -u USERNAME
test.py: error: the following arguments are required: -u/--username

Process finished with exit code 2`

**Comment by Lior-Asher** [comment]
run the app like so:
./app.py -u your_username
then you will be promped need to enter your password

username and password are the ones you use to login to your Artifactory account

**Comment by sharathkumarnp** [comment]
Okay.

The Ping test is successful 
the rest options are failing due to  authentication error, not able to get artifactory version, storage info.. user creation

Error:

`Get Storage Info:
{'errors': [{'status': 401, 'message': 'Authentication is required'}]}
`

**Comment by sharathkumarnp** [comment]
Have entered all credentials correctly..also given admin permission to that user.

**Comment by Lior-Asher** [comment]
if I remember correctly, ping does not require authentication, so it always works.
other API calls require a token.
_get_token_for_group method retrieves a token for users in group 'administrators'.
my guess is you can't get a token from Artifactory.
add the user to 'administrators' group, see if that helps

**Comment by sharathkumarnp** [comment]
Great!!

I changed the group to 'adusers' and provide administrator permission.. and added a local user.. it worked..
Thanks for your help!! buddy
